/**
 * Datos iniciales tomados del diseño aprobado (handoff-claude-code/diseno).
 * Precios, duraciones e itinerarios son de ejemplo: el cliente debe revisarlos.
 * Se usan para sembrar la base de datos y como respaldo si Supabase no responde.
 */
import type { L10n, SiteData, Tour } from "./types";

const l = (es: string, en: string): L10n => ({ es, en });

const photo = (caption: L10n, tone: string, url: string | null = null) => ({ url, caption, tone });

const tours: Tour[] = [
  {
    id: "t1",
    slug: "venaditos-cascadas",
    name: l("Venaditos / Cascadas", "Venaditos / Waterfalls"),
    category: "senderismo",
    short: l(
      "Sendero entre encinos y arroyos hasta las cascadas escondidas de la sierra.",
      "A trail through oak forest and streams to the hidden waterfalls of the range.",
    ),
    description: l(
      "Un recorrido por el bosque de encino y los arroyos de la sierra hasta llegar a las cascadas de la zona de los Venaditos. El sendero combina tramos planos con subidas moderadas y pasos entre rocas.\n\nEs el tour ideal para desconectarte: escucharás el agua antes de verla, aprenderás a reconocer plantas de la región y tendrás tiempo para descansar junto a las pozas.",
      "A walk through the oak forest and streams of the range to the waterfalls of the Venaditos area. The trail mixes flat stretches with moderate climbs and rocky passages.\n\nIt's the perfect tour to disconnect: you'll hear the water before you see it, learn to recognize local plants and have time to rest by the pools.",
    ),
    price: 650,
    durationHours: 5,
    difficulty: "moderada",
    groupMax: 10,
    departureTime: "8:00 a.m.",
    meetingPoint: l("Centro de Tepoztlán", "Downtown Tepoztlán"),
    scheduleDays: l("Martes a domingo", "Tuesday to Sunday"),
    minAge: 10,
    badge: l("Temporada de lluvias", "Rainy season"),
    photos: [
      photo(l("Cascada principal", "Main waterfall"), "#2E5A4C", "/portadas/venaditos-cascadas.webp"),
      photo(l("Sendero entre encinos", "Trail through the oaks"), "#4E6540"),
      photo(l("Poza para nadar", "Swimming pool"), "#3F5C5E"),
      photo(l("Cruce del arroyo", "Stream crossing"), "#5E6B45"),
      photo(l("Vista del valle", "Valley view"), "#8F6E42"),
    ],
    itinerary: [
      { time: "8:00", title: l("Encuentro en el centro", "Meet downtown"), detail: l("Te recibimos en el centro de Tepoztlán, conoces a tu guía y revisamos el equipo.", "We meet in downtown Tepoztlán, you meet your guide and we check the gear.") },
      { time: "8:30", title: l("Traslado al sendero", "Ride to the trailhead"), detail: l("Breve traslado en vehículo hasta la entrada del bosque.", "A short drive to the forest entrance.") },
      { time: "9:00", title: l("Caminata entre encinos", "Hike through the oaks"), detail: l("Hora y media de sendero con paradas para fotos y para conocer la flora de la sierra.", "An hour and a half on the trail with stops for photos and to learn about the local plants.") },
      { time: "10:45", title: l("Cascadas y pozas", "Waterfalls and pools"), detail: l("Tiempo libre para descansar, nadar en temporada y disfrutar un refrigerio.", "Free time to rest, swim in season and enjoy a snack.") },
      { time: "12:30", title: l("Regreso al pueblo", "Back to town"), detail: l("Volvemos por otro tramo del sendero y llegamos al centro cerca de la 1:00 p.m.", "We return along a different stretch of the trail and reach downtown around 1:00 p.m.") },
    ],
    includes: {
      es: ["Guía local durante todo el recorrido", "Traslado al inicio del sendero", "Refrigerio y agua", "Bastones de senderismo", "Fotos del recorrido"],
      en: ["Local guide for the whole tour", "Ride to the trailhead", "Snack and water", "Hiking poles", "Photos of the tour"],
    },
    bring: {
      es: ["Calzado para sendero", "Traje de baño y toalla", "Protector solar y gorra", "1.5 litros de agua", "Impermeable en lluvias"],
      en: ["Trail shoes", "Swimsuit and towel", "Sunscreen and cap", "1.5 liters of water", "Rain jacket in rainy season"],
    },
    waMessage: l(
      "¡Hola TepozTours! Quiero reservar el tour Venaditos / Cascadas. ¿Qué fechas tienen disponibles?",
      "Hi TepozTours! I'd like to book the Venaditos / Waterfalls tour. What dates do you have available?",
    ),
    tone: "#2E5A4C",
    mapX: 130,
    mapY: 330,
    pinLabel: l("Venaditos", "Venaditos"),
    active: true,
    inCarousel: true,
    sortOrder: 1,
  },
  {
    id: "t2",
    slug: "amanecer",
    name: l("Amanecer", "Sunrise"),
    category: "senderismo",
    short: l(
      "Salida de madrugada para ver el sol encender los cerros desde un mirador.",
      "An early start to watch the sun light up the hills from a lookout.",
    ),
    description: l(
      "Salimos antes del alba con lámpara frontal para subir por una vereda tranquila hasta un mirador natural sobre el valle. Desde ahí verás cómo la primera luz enciende las paredes de roca de la sierra.\n\nMientras el sol sale compartimos café de olla y pan dulce. Es una caminata corta pero con subidas, pensada para empezar el día con calma y con la mejor vista de Tepoztlán.",
      "We head out before dawn with headlamps and climb a quiet path to a natural lookout above the valley. From there you'll watch the first light set the range's rock walls aglow.\n\nWhile the sun comes up we share café de olla and sweet bread. It's a short hike with some climbs, designed to start the day calmly with the best view of Tepoztlán.",
    ),
    price: 550,
    durationHours: 3.5,
    difficulty: "moderada",
    groupMax: 12,
    departureTime: "5:30 a.m.",
    meetingPoint: l("Centro de Tepoztlán", "Downtown Tepoztlán"),
    scheduleDays: l("Todos los días", "Every day"),
    minAge: 8,
    badge: l("Café de olla incluido", "Café de olla included"),
    photos: [
      photo(l("Amanecer desde el mirador", "Sunrise from the lookout"), "#B8703A", "/portadas/amanecer.webp"),
      photo(l("Subida con lámpara", "Climbing by headlamp"), "#5A4632"),
      photo(l("Café de olla", "Café de olla"), "#8F6E42"),
      photo(l("Paredes de roca", "Rock walls"), "#9C4A2F"),
      photo(l("El valle al despertar", "The valley waking up"), "#4E6540"),
    ],
    itinerary: [
      { time: "5:30", title: l("Encuentro en el centro", "Meet downtown"), detail: l("Te entregamos lámpara frontal y revisamos el clima antes de salir.", "We hand out headlamps and check the weather before heading out.") },
      { time: "5:45", title: l("Subida en la penumbra", "Climb in the dark"), detail: l("Caminata de unos 50 minutos por una vereda con subidas moderadas.", "About 50 minutes on a path with moderate climbs.") },
      { time: "6:45", title: l("Amanecer en el mirador", "Sunrise at the lookout"), detail: l("Vemos salir el sol sobre el valle con café de olla y pan dulce.", "We watch the sun rise over the valley with café de olla and sweet bread.") },
      { time: "7:40", title: l("Descenso", "Descent"), detail: l("Bajamos con luz de día, con paradas para fotos.", "We head down in daylight, stopping for photos.") },
      { time: "9:00", title: l("Regreso al centro", "Back downtown"), detail: l("Llegamos al centro a tiempo para desayunar en el mercado.", "We're back downtown in time for breakfast at the market.") },
    ],
    includes: {
      es: ["Guía local", "Lámpara frontal", "Café de olla y pan dulce", "Agua", "Fotos del amanecer"],
      en: ["Local guide", "Headlamp", "Café de olla and sweet bread", "Water", "Sunrise photos"],
    },
    bring: {
      es: ["Calzado para sendero", "Chamarra ligera (hace frío al amanecer)", "Agua", "Gorra y protector solar", "Mochila pequeña"],
      en: ["Trail shoes", "Light jacket (it's cold at dawn)", "Water", "Cap and sunscreen", "Small backpack"],
    },
    waMessage: l(
      "¡Hola TepozTours! Me interesa el tour Amanecer. ¿A qué hora es el punto de encuentro y qué días salen?",
      "Hi TepozTours! I'm interested in the Sunrise tour. What time do you meet and which days does it run?",
    ),
    tone: "#B8703A",
    mapX: 500,
    mapY: 250,
    pinLabel: l("Amanecer", "Sunrise"),
    active: true,
    inCarousel: true,
    sortOrder: 2,
  },
  {
    id: "t3",
    slug: "cuevas-volcanicas",
    name: l("Cuevas volcánicas", "Volcanic Caves"),
    category: "aventura",
    short: l(
      "Recorre túneles de lava con casco y lámpara, guiado paso a paso.",
      "Explore lava tubes with a helmet and headlamp, guided step by step.",
    ),
    description: l(
      "Entra con casco y lámpara a los túneles que dejó la lava hace miles de años. Recorremos galerías amplias y pasos estrechos, siempre con un guía que conoce cada tramo.\n\nEn el camino te contamos cómo se formaron las cuevas y qué animales viven en ellas. Es una aventura bajo tierra apta para quien no le teme a ensuciarse un poco.",
      "Enter the tunnels left by lava thousands of years ago with a helmet and headlamp. We walk through wide galleries and narrow passages, always with a guide who knows every stretch.\n\nAlong the way we explain how the caves formed and which animals live in them. It's an underground adventure for anyone who doesn't mind getting a little dirty.",
    ),
    price: 700,
    durationHours: 4,
    difficulty: "moderada",
    groupMax: 8,
    departureTime: "9:00 a.m.",
    meetingPoint: l("Centro de Tepoztlán", "Downtown Tepoztlán"),
    scheduleDays: l("Miércoles a domingo", "Wednesday to Sunday"),
    minAge: 12,
    badge: l("Equipo incluido", "Gear included"),
    photos: [
      photo(l("Entrada a la cueva", "Cave entrance"), "#3D3632", "/portadas/cuevas-volcanicas.webp"),
      photo(l("Túnel de lava", "Lava tube"), "#2B2724"),
      photo(l("Con casco y lámpara", "Helmet and headlamp"), "#5A4632"),
      photo(l("Galería principal", "Main gallery"), "#4A3F38"),
      photo(l("Salida al bosque", "Out to the forest"), "#4E6540"),
    ],
    itinerary: [
      { time: "9:00", title: l("Encuentro y equipo", "Meet and gear up"), detail: l("Te entregamos casco, lámpara y guantes, y damos las indicaciones de seguridad.", "We hand out helmets, headlamps and gloves and go over safety.") },
      { time: "9:30", title: l("Traslado al campo de lava", "Ride to the lava field"), detail: l("Traslado corto hasta la zona de cuevas.", "A short drive to the cave area.") },
      { time: "10:00", title: l("Dentro de las cuevas", "Inside the caves"), detail: l("Recorremos túneles y galerías con paradas para explicar su formación.", "We explore tunnels and galleries, stopping to explain how they formed.") },
      { time: "11:45", title: l("Salida y refrigerio", "Out and snack"), detail: l("Descanso al aire libre con agua y refrigerio.", "A rest outdoors with water and a snack.") },
      { time: "13:00", title: l("Regreso al centro", "Back downtown"), detail: l("Llegamos al centro de Tepoztlán.", "We arrive back in downtown Tepoztlán.") },
    ],
    includes: {
      es: ["Guía especializado", "Casco y lámpara", "Guantes", "Traslado", "Refrigerio y agua"],
      en: ["Specialized guide", "Helmet and headlamp", "Gloves", "Transportation", "Snack and water"],
    },
    bring: {
      es: ["Ropa que se pueda ensuciar", "Tenis con buen agarre", "Pantalón largo", "Agua", "Muda de ropa"],
      en: ["Clothes that can get dirty", "Sneakers with good grip", "Long pants", "Water", "Change of clothes"],
    },
    waMessage: l(
      "¡Hola TepozTours! Quiero reservar el tour Cuevas volcánicas. ¿Necesito llevar algo especial?",
      "Hi TepozTours! I'd like to book the Volcanic Caves tour. Do I need to bring anything special?",
    ),
    tone: "#3D3632",
    mapX: 480,
    mapY: 610,
    pinLabel: l("Cuevas", "Caves"),
    active: true,
    inCarousel: true,
    sortOrder: 3,
  },
  {
    id: "t4",
    slug: "cabalgata",
    name: l("Cabalgata", "Horseback Ride"),
    category: "aventura",
    short: l(
      "A caballo por veredas, campos y miradores al pie de la sierra.",
      "On horseback along paths, fields and lookouts at the foot of the range.",
    ),
    description: l(
      "Recorre a caballo veredas, campos de cultivo y miradores al pie de la sierra. Nuestros caballos son mansos y están acostumbrados a jinetes sin experiencia.\n\nAntes de salir te presentamos a tu caballo y te enseñamos lo básico. Avanzamos al paso, con tiempo para disfrutar el paisaje y tomar fotos en el mirador.",
      "Ride along paths, farm fields and lookouts at the foot of the range. Our horses are gentle and used to riders with no experience.\n\nBefore heading out we introduce you to your horse and teach you the basics. We ride at a walking pace, with time to enjoy the scenery and take photos at the lookout.",
    ),
    price: 900,
    durationHours: 3,
    difficulty: "facil",
    groupMax: 8,
    departureTime: "10:00 a.m.",
    meetingPoint: l("Rancho en las afueras (te enviamos la ubicación)", "Ranch on the outskirts (we'll send the location)"),
    scheduleDays: l("Todos los días", "Every day"),
    minAge: 7,
    badge: l("Ideal para principiantes", "Great for beginners"),
    photos: [
      photo(l("Por las veredas", "Along the paths"), "#8F6E42", "/portadas/cabalgata.webp"),
      photo(l("Caballos mansos", "Gentle horses"), "#6B4F32"),
      photo(l("Campos de cultivo", "Farm fields"), "#7C8A4E"),
      photo(l("Mirador de la sierra", "Range lookout"), "#4E6540"),
      photo(l("De regreso al rancho", "Back to the ranch"), "#B8703A"),
    ],
    itinerary: [
      { time: "10:00", title: l("Encuentro en el rancho", "Meet at the ranch"), detail: l("Te recibimos en el rancho y ajustamos casco y montura.", "We welcome you at the ranch and fit your helmet and saddle.") },
      { time: "10:20", title: l("Conoce a tu caballo", "Meet your horse"), detail: l("Indicaciones básicas para montar con seguridad.", "Basic tips to ride safely.") },
      { time: "10:40", title: l("Cabalgata por veredas", "Ride along the paths"), detail: l("Avanzamos al paso entre campos y arroyos.", "We ride at a walk among fields and streams.") },
      { time: "11:40", title: l("Mirador al pie de la sierra", "Lookout at the foot of the range"), detail: l("Parada para descansar y tomar fotos.", "A stop to rest and take photos.") },
      { time: "13:00", title: l("Regreso al rancho", "Back to the ranch"), detail: l("Volvemos por otra vereda y cerramos con agua fresca.", "We return by another path and finish with a cool drink.") },
    ],
    includes: {
      es: ["Guía y caballerango", "Caballo manso y equipo", "Casco", "Agua", "Fotos del recorrido"],
      en: ["Guide and wrangler", "Gentle horse and gear", "Helmet", "Water", "Photos of the ride"],
    },
    bring: {
      es: ["Pantalón largo", "Zapato cerrado", "Gorra y protector solar", "Agua", "Ropa cómoda"],
      en: ["Long pants", "Closed-toe shoes", "Cap and sunscreen", "Water", "Comfortable clothes"],
    },
    waMessage: l(
      "¡Hola TepozTours! Quisiera reservar la Cabalgata. ¿Tienen lugar este fin de semana?",
      "Hi TepozTours! I'd like to book the Horseback Ride. Do you have space this weekend?",
    ),
    tone: "#8F6E42",
    mapX: 150,
    mapY: 590,
    pinLabel: l("Cabalgata", "Horseback"),
    active: true,
    inCarousel: true,
    sortOrder: 4,
  },
  {
    id: "t5",
    slug: "recorrido-cultural",
    name: l("Recorrido cultural", "Cultural Walk"),
    category: "cultura",
    short: l(
      "El pueblo mágico a pie: mercado, ex convento y leyendas del Tepozteco.",
      "The Pueblo Mágico on foot: market, former convent and legends of the Tepozteco.",
    ),
    description: l(
      "Descubre el pueblo mágico a pie: su mercado, el ex convento de la Natividad y las leyendas del Tepozteco contadas por un guía local.\n\nCaminamos por calles empedradas, probamos antojitos del mercado y terminamos con una nieve artesanal. Un recorrido tranquilo, ideal para toda la familia.",
      "Discover the Pueblo Mágico on foot: its market, the former Convent of the Nativity and the legends of the Tepozteco told by a local guide.\n\nWe stroll cobblestone streets, taste snacks at the market and finish with an artisanal ice cream. A relaxed walk, perfect for the whole family.",
    ),
    price: 450,
    durationHours: 2.5,
    difficulty: "facil",
    groupMax: 15,
    departureTime: "10:00 a.m.",
    meetingPoint: l("Zócalo de Tepoztlán", "Tepoztlán main square"),
    scheduleDays: l("Viernes a domingo", "Friday to Sunday"),
    minAge: null,
    badge: l("Pueblo mágico", "Pueblo Mágico"),
    photos: [
      photo(l("Ex convento de la Natividad", "Former Convent of the Nativity"), "#9C4A2F", "/portadas/recorrido-cultural.webp"),
      photo(l("Mercado de Tepoztlán", "Tepoztlán market"), "#B8703A"),
      photo(l("Calles empedradas", "Cobblestone streets"), "#8F6E42"),
      photo(l("Artesanías locales", "Local crafts"), "#7A4634"),
      photo(l("Nieve artesanal", "Artisanal ice cream"), "#C98A4B"),
    ],
    itinerary: [
      { time: "10:00", title: l("Encuentro en el zócalo", "Meet at the main square"), detail: l("Conoces a tu guía y te contamos la historia del pueblo.", "You meet your guide and hear the town's story.") },
      { time: "10:15", title: l("Mercado de Tepoztlán", "Tepoztlán market"), detail: l("Recorremos los puestos y probamos antojitos tradicionales.", "We browse the stalls and taste traditional snacks.") },
      { time: "11:00", title: l("Ex convento de la Natividad", "Former Convent of the Nativity"), detail: l("Visita guiada a uno de los conventos del siglo XVI de Morelos.", "A guided visit to one of Morelos' 16th-century convents.") },
      { time: "11:45", title: l("Leyendas del Tepozteco", "Legends of the Tepozteco"), detail: l("Historias del dios del pulque y de la pirámide en la cima.", "Stories of the god of pulque and the pyramid on the summit.") },
      { time: "12:30", title: l("Cierre con nieve", "Ice cream to finish"), detail: l("Terminamos con una nieve artesanal del pueblo.", "We finish with an artisanal ice cream from town.") },
    ],
    includes: {
      es: ["Guía local", "Degustación en el mercado", "Nieve artesanal", "Agua"],
      en: ["Local guide", "Market tasting", "Artisanal ice cream", "Water"],
    },
    bring: {
      es: ["Calzado cómodo", "Gorra y protector solar", "Agua", "Efectivo para artesanías"],
      en: ["Comfortable shoes", "Cap and sunscreen", "Water", "Cash for crafts"],
    },
    waMessage: l(
      "¡Hola TepozTours! Me gustaría hacer el Recorrido cultural por el pueblo. ¿Qué horarios tienen?",
      "Hi TepozTours! I'd like to do the Cultural Walk through town. What times do you have?",
    ),
    tone: "#9C4A2F",
    mapX: 320,
    mapY: 450,
    pinLabel: l("Cultural", "Cultural"),
    active: true,
    inCarousel: true,
    sortOrder: 5,
  },
  {
    id: "t6",
    slug: "cerro-tepozteco",
    name: l("Cerro Tepozteco", "Tepozteco Hill"),
    category: "senderismo",
    short: l(
      "Subida por el sendero de piedra hasta la pirámide y la mejor vista del valle.",
      "A climb up the stone trail to the pyramid and the best view of the valley.",
    ),
    description: l(
      "Sube el sendero de piedra hasta la pirámide en la cima y gánate la vista más famosa de Tepoztlán. Es una subida exigente, con escalones altos y tramos empinados.\n\nVamos a tu ritmo, con paradas para recuperar el aliento y conocer la historia del Tepozteco. En la cima tendrás tiempo para descansar y disfrutar el paisaje.",
      "Climb the stone trail to the pyramid at the top and earn the most famous view in Tepoztlán. It's a demanding climb with high steps and steep stretches.\n\nWe go at your pace, with stops to catch your breath and learn the history of the Tepozteco. At the top you'll have time to rest and enjoy the view.",
    ),
    price: 500,
    durationHours: 4,
    difficulty: "exigente",
    groupMax: 12,
    departureTime: "7:30 a.m.",
    meetingPoint: l("Centro de Tepoztlán", "Downtown Tepoztlán"),
    scheduleDays: l("Martes a domingo", "Tuesday to Sunday"),
    minAge: 12,
    badge: l("La vista más famosa", "The most famous view"),
    photos: [
      photo(l("Pirámide del Tepozteco", "Tepozteco pyramid"), "#4E6540", "/portadas/cerro-tepozteco.webp"),
      photo(l("Sendero de piedra", "Stone trail"), "#6B5A3C"),
      photo(l("Vista desde la cima", "View from the top"), "#8F6E42"),
      photo(l("Descanso a medio camino", "Rest halfway up"), "#3F5C5E"),
      photo(l("El valle de Tepoztlán", "The Tepoztlán valley"), "#2E5A4C"),
    ],
    itinerary: [
      { time: "7:30", title: l("Encuentro en el centro", "Meet downtown"), detail: l("Calentamiento y recomendaciones para la subida.", "Warm-up and tips for the climb.") },
      { time: "7:45", title: l("Inicio del sendero", "Start of the trail"), detail: l("Subida por el sendero de piedra entre árboles.", "Climb up the stone trail through the trees.") },
      { time: "9:15", title: l("Llegada a la pirámide", "Reaching the pyramid"), detail: l("Recorremos la cima y la zona de la pirámide.", "We explore the summit and the pyramid area.") },
      { time: "10:00", title: l("Historia y descanso", "History and rest"), detail: l("Te contamos la historia del Tepozteco con el valle a tus pies.", "We tell the story of the Tepozteco with the valley at your feet.") },
      { time: "11:30", title: l("Descenso y regreso", "Descent and return"), detail: l("Bajamos con calma y llegamos al centro.", "We head down calmly and return downtown.") },
    ],
    includes: {
      es: ["Guía local", "Agua y fruta", "Bastones de senderismo", "Fotos en la cima"],
      en: ["Local guide", "Water and fruit", "Hiking poles", "Photos at the top"],
    },
    bring: {
      es: ["Calzado para sendero", "2 litros de agua", "Gorra y protector solar", "Ropa ligera", "Snack energético"],
      en: ["Trail shoes", "2 liters of water", "Cap and sunscreen", "Light clothes", "Energy snack"],
    },
    waMessage: l(
      "¡Hola TepozTours! Quiero subir al Cerro Tepozteco con ustedes. ¿Qué fechas hay disponibles?",
      "Hi TepozTours! I'd like to climb Tepozteco Hill with you. What dates are available?",
    ),
    tone: "#4E6540",
    mapX: 340,
    mapY: 215,
    pinLabel: l("Tepozteco", "Tepozteco"),
    active: true,
    inCarousel: true,
    sortOrder: 6,
  },
  {
    id: "t7",
    slug: "sobre-2-ruedas",
    name: l("Sobre 2 ruedas (ruta bici)", "On 2 Wheels (bike route)"),
    category: "aventura",
    short: l(
      "Ruta en bici de montaña por terracería, campos y pueblos vecinos.",
      "A mountain bike route along dirt roads, fields and nearby villages.",
    ),
    description: l(
      "Pedalea por caminos de terracería, campos y pueblos vecinos en una ruta de montaña. Bici, casco y guantes incluidos, ajustados a tu medida antes de salir.\n\nLa ruta tiene subidas cortas y bajadas divertidas. Vamos con guía y apoyo mecánico, con paradas para descansar y conocer los pueblos del valle.",
      "Ride dirt roads, fields and nearby villages on a mountain route. Bike, helmet and gloves included, fitted to you before we set off.\n\nThe route has short climbs and fun descents. We ride with a guide and mechanical support, with stops to rest and visit the valley's villages.",
    ),
    price: 750,
    durationHours: 3,
    difficulty: "moderada",
    groupMax: 8,
    departureTime: "8:30 a.m.",
    meetingPoint: l("Centro de Tepoztlán", "Downtown Tepoztlán"),
    scheduleDays: l("Sábado y domingo", "Saturday and Sunday"),
    minAge: 14,
    badge: l("Bici y casco incluidos", "Bike and helmet included"),
    photos: [
      photo(l("Terracería al pie de la sierra", "Dirt road below the range"), "#3F5C5E", "/portadas/sobre-2-ruedas.webp"),
      photo(l("Ajuste de bicis", "Bike fitting"), "#4A5A5C"),
      photo(l("Entre campos", "Through the fields"), "#7C8A4E"),
      photo(l("Pueblo vecino", "Neighboring village"), "#9C4A2F"),
      photo(l("Bajada final", "Final descent"), "#4E6540"),
    ],
    itinerary: [
      { time: "8:30", title: l("Encuentro y ajuste de bici", "Meet and bike fitting"), detail: l("Ajustamos bici y casco, y repasamos las señales de ruta.", "We fit your bike and helmet and review the route signals.") },
      { time: "9:00", title: l("Salida por terracería", "Off along the dirt roads"), detail: l("Primer tramo por caminos de tierra al pie de la sierra.", "First stretch on dirt roads at the foot of the range.") },
      { time: "10:00", title: l("Campos y pueblos vecinos", "Fields and nearby villages"), detail: l("Pedaleamos entre campos hasta un pueblo vecino.", "We ride through fields to a neighboring village.") },
      { time: "10:45", title: l("Descanso y refrigerio", "Rest and snack"), detail: l("Parada para hidratarnos y comer algo.", "A stop to hydrate and have a bite.") },
      { time: "11:30", title: l("Regreso al centro", "Back downtown"), detail: l("Volvemos por una ruta con bajadas suaves.", "We return on a route with gentle descents.") },
    ],
    includes: {
      es: ["Bici de montaña", "Casco y guantes", "Guía y apoyo mecánico", "Refrigerio y agua"],
      en: ["Mountain bike", "Helmet and gloves", "Guide and mechanical support", "Snack and water"],
    },
    bring: {
      es: ["Ropa deportiva", "Tenis", "Lentes de sol", "Protector solar", "Agua"],
      en: ["Sportswear", "Sneakers", "Sunglasses", "Sunscreen", "Water"],
    },
    waMessage: l(
      "¡Hola TepozTours! Me interesa la ruta Sobre 2 ruedas. ¿Incluye bici y casco?",
      "Hi TepozTours! I'm interested in the On 2 Wheels route. Are the bike and helmet included?",
    ),
    tone: "#3F5C5E",
    mapX: 250,
    mapY: 720,
    pinLabel: l("Ruta bici", "Bike route"),
    active: true,
    inCarousel: true,
    sortOrder: 7,
  },
  {
    id: "t8",
    slug: "temazcal",
    name: l("Temazcal", "Temazcal"),
    category: "bienestar",
    short: l(
      "Ceremonia tradicional de vapor con hierbas, guiada por un temazcalero.",
      "A traditional steam ceremony with herbs, led by a temazcal guide.",
    ),
    description: l(
      "Una ceremonia tradicional de vapor con hierbas medicinales, guiada por un temazcalero del pueblo. El temazcal es un baño de vapor ancestral para descansar el cuerpo y la mente.\n\nAntes de entrar hacemos una limpia con hierbas; al salir descansas con un té caliente. Sal renovado y con otra energía.",
      "A traditional steam ceremony with medicinal herbs, led by a local temazcal guide. The temazcal is an ancestral steam bath to rest body and mind.\n\nBefore going in we do a cleansing with herbs; afterwards you rest with a hot tea. You'll leave renewed.",
    ),
    price: 600,
    durationHours: 2,
    difficulty: "facil",
    groupMax: 10,
    departureTime: "5:00 p.m.",
    meetingPoint: l("Centro de Tepoztlán", "Downtown Tepoztlán"),
    scheduleDays: l("Jueves a domingo", "Thursday to Sunday"),
    minAge: 16,
    badge: l("Ceremonia tradicional", "Traditional ceremony"),
    photos: [
      photo(l("Temazcal tradicional", "Traditional temazcal"), "#7A4634", "/portadas/temazcal.webp"),
      photo(l("Hierbas medicinales", "Medicinal herbs"), "#5E6B45"),
      photo(l("Piedras volcánicas", "Volcanic stones"), "#3D3632"),
      photo(l("Té de hierbas", "Herbal tea"), "#8F6E42"),
      photo(l("Descanso al atardecer", "Rest at sunset"), "#B8703A"),
    ],
    itinerary: [
      { time: "17:00", title: l("Bienvenida", "Welcome"), detail: l("Te explicamos el sentido de la ceremonia y cómo prepararte.", "We explain the meaning of the ceremony and how to prepare.") },
      { time: "17:20", title: l("Limpia con hierbas", "Herbal cleansing"), detail: l("Limpia tradicional con hierbas y copal.", "A traditional cleansing with herbs and copal.") },
      { time: "17:40", title: l("Ceremonia de vapor", "Steam ceremony"), detail: l("Entramos al temazcal guiados por el temazcalero.", "We enter the temazcal led by the temazcal guide.") },
      { time: "18:30", title: l("Descanso y té", "Rest and tea"), detail: l("Descanso al aire libre con té de hierbas.", "A rest outdoors with herbal tea.") },
      { time: "19:00", title: l("Cierre", "Closing"), detail: l("Cerramos la ceremonia y regresas renovado.", "We close the ceremony and you head back renewed.") },
    ],
    includes: {
      es: ["Temazcalero del pueblo", "Hierbas medicinales", "Té de hierbas", "Toalla"],
      en: ["Local temazcal guide", "Medicinal herbs", "Herbal tea", "Towel"],
    },
    bring: {
      es: ["Traje de baño", "Sandalias", "Muda de ropa", "Agua"],
      en: ["Swimsuit", "Sandals", "Change of clothes", "Water"],
    },
    waMessage: l(
      "¡Hola TepozTours! Quiero reservar una sesión de Temazcal. ¿Para cuántas personas es?",
      "Hi TepozTours! I'd like to book a Temazcal session. How many people is it for?",
    ),
    tone: "#7A4634",
    mapX: 420,
    mapY: 520,
    pinLabel: l("Temazcal", "Temazcal"),
    active: true,
    inCarousel: true,
    sortOrder: 8,
  },
];

/** Texto del hero por tour, tomado del diseño. */
const heroCopy: Record<string, { line1: L10n; line2: L10n; eyebrow: L10n; description: L10n }> = {
  t1: {
    line1: l("Venaditos /", "Venaditos /"),
    line2: l("Cascadas", "Waterfalls"),
    eyebrow: l("Tepoztlán, Morelos", "Tepoztlán, Morelos"),
    description: l(
      "Camina entre encinos, cruza arroyos y refréscate en las cascadas escondidas de la sierra. En temporada de lluvias es otro mundo.",
      "Hike through oak forest, cross streams and cool off at the hidden waterfalls of the range. In the rainy season it's another world.",
    ),
  },
  t2: {
    line1: l("Amanecer", "Sunrise"),
    line2: l("", ""),
    eyebrow: l("Tepoztlán, Morelos", "Tepoztlán, Morelos"),
    description: l(
      "Salimos antes del alba para subir a un mirador y ver cómo el sol enciende las paredes de roca del valle. Café de olla incluido.",
      "We head out before dawn to climb to a lookout and watch the sun light up the valley's rock walls. Café de olla included.",
    ),
  },
  t3: {
    line1: l("Cuevas", "Volcanic"),
    line2: l("volcánicas", "Caves"),
    eyebrow: l("Tepoztlán, Morelos", "Tepoztlán, Morelos"),
    description: l(
      "Entra con casco y lámpara a los túneles que dejó la lava hace miles de años. Una aventura bajo tierra, guiada paso a paso.",
      "Enter the tunnels left by lava thousands of years ago with a helmet and headlamp. An underground adventure, guided step by step.",
    ),
  },
  t4: {
    line1: l("Cabalgata", "Horseback"),
    line2: l("", "Ride"),
    eyebrow: l("Tepoztlán, Morelos", "Tepoztlán, Morelos"),
    description: l(
      "Recorre a caballo veredas, campos de cultivo y miradores al pie de la sierra. Caballos mansos, ideales para principiantes.",
      "Ride along paths, farm fields and lookouts at the foot of the range. Gentle horses, perfect for beginners.",
    ),
  },
  t5: {
    line1: l("Recorrido", "Cultural"),
    line2: l("cultural", "Walk"),
    eyebrow: l("Pueblo mágico", "Pueblo Mágico"),
    description: l(
      "Descubre el pueblo mágico a pie: su mercado, el ex convento de la Natividad y las leyendas del Tepozteco contadas por un guía local.",
      "Discover the Pueblo Mágico on foot: its market, the former Convent of the Nativity and the legends of the Tepozteco told by a local guide.",
    ),
  },
  t6: {
    line1: l("Cerro", "Tepozteco"),
    line2: l("Tepozteco", "Hill"),
    eyebrow: l("Tepoztlán, Morelos", "Tepoztlán, Morelos"),
    description: l(
      "Sube el sendero de piedra hasta la pirámide en la cima y gánate la vista más famosa de Tepoztlán.",
      "Climb the stone trail to the pyramid at the top and earn the most famous view in Tepoztlán.",
    ),
  },
  t7: {
    line1: l("Sobre 2", "On 2"),
    line2: l("ruedas", "Wheels"),
    eyebrow: l("Ruta bici", "Bike route"),
    description: l(
      "Pedalea por caminos de terracería, campos y pueblos vecinos en una ruta de montaña. Bici y casco incluidos.",
      "Ride dirt roads, fields and nearby villages on a mountain route. Bike and helmet included.",
    ),
  },
  t8: {
    line1: l("Temazcal", "Temazcal"),
    line2: l("", ""),
    eyebrow: l("Tepoztlán, Morelos", "Tepoztlán, Morelos"),
    description: l(
      "Una ceremonia tradicional de vapor con hierbas medicinales, guiada por un temazcalero del pueblo. Sal renovado.",
      "A traditional steam ceremony with medicinal herbs, led by a local temazcal guide. You'll leave renewed.",
    ),
  },
};

export const seedData: SiteData = {
  settings: {
    name: "TepozTours",
    slogan: l("Tours con guías locales en Tepoztlán", "Tours with local guides in Tepoztlán"),
    email: "",
    hours: l("Todos los días · [7:00 a 19:00]", "Every day · [7:00 a.m. to 7:00 p.m.]"),
    address: l("[Dirección], Centro, Tepoztlán, Mor.", "[Address], Downtown Tepoztlán, Mor."),
    whatsapp: "",
    waMessage: l(
      "¡Hola TepozTours! Quiero información para reservar un tour.",
      "Hi TepozTours! I'd like some information to book a tour.",
    ),
    logoUrl: null,
    aboutPhotos: { main: null, secondary: null },
    colors: { forest: "#1F3A2E", terra: "#B4532A", amber: "#E9A23B", sand: "#E3D0B0", cream: "#F6EFE3" },
    social: { facebook: "", instagram: "", tiktok: "" },
    showSocial: true,
    heroAutoplay: true,
    heroInterval: 6,
  },
  tours,
  slides: tours.map((tour, i) => ({
    id: `s${i + 1}`,
    tourId: tour.id,
    ...heroCopy[tour.id],
    image: null,
    visible: true,
    sortOrder: i + 1,
  })),
  gallery: [
    { id: "g1", image: null, caption: l("Cascadas en temporada de lluvias", "Waterfalls in the rainy season"), tone: "#2E5A4C", visible: true, sortOrder: 1 },
    { id: "g2", image: null, caption: l("Amanecer en el mirador", "Sunrise at the lookout"), tone: "#B8703A", visible: true, sortOrder: 2 },
    { id: "g3", image: null, caption: l("Dentro de las cuevas", "Inside the caves"), tone: "#3D3632", visible: true, sortOrder: 3 },
    { id: "g4", image: null, caption: l("Temazcal tradicional", "Traditional temazcal"), tone: "#7A4634", visible: true, sortOrder: 4 },
    { id: "g5", image: null, caption: l("Pirámide del Tepozteco", "Tepozteco pyramid"), tone: "#4E6540", visible: true, sortOrder: 5 },
  ],
  testimonials: [
    {
      id: "r1",
      quote: l(
        "Subir al Tepozteco con alguien que conoce cada piedra hizo toda la diferencia. Fuimos a nuestro ritmo y con muchas historias.",
        "Climbing the Tepozteco with someone who knows every stone made all the difference. We went at our own pace and heard lots of stories.",
      ),
      name: "",
      tour: l("Tour Cerro Tepozteco", "Tepozteco Hill tour"),
      tone: "#CDB891",
      visible: true,
      sortOrder: 1,
    },
    {
      id: "r2",
      quote: l(
        "Reservamos por WhatsApp en cinco minutos. Ver el amanecer desde el mirador fue lo mejor del viaje.",
        "We booked on WhatsApp in five minutes. Watching the sunrise from the lookout was the best part of the trip.",
      ),
      name: "",
      tour: l("Tour Amanecer", "Sunrise tour"),
      tone: "#E9A23B",
      visible: true,
      sortOrder: 2,
    },
    {
      id: "r3",
      quote: l(
        "Las cuevas volcánicas son otro mundo. Todo el equipo incluido y el guía muy atento en cada tramo.",
        "The volcanic caves are another world. All the gear was included and the guide was attentive every step of the way.",
      ),
      name: "",
      tour: l("Tour Cuevas volcánicas", "Volcanic Caves tour"),
      tone: "#B7BF98",
      visible: true,
      sortOrder: 3,
    },
  ],
  guides: [
    { id: "p1", name: "Mateo", role: l("Senderismo y Cerro Tepozteco", "Hiking and Tepozteco Hill"), tags: [l("Tepozteco", "Tepozteco"), l("Amanecer", "Sunrise")], photo: null, tone: "#4E6540", visible: true, sortOrder: 1 },
    { id: "p2", name: "Citlali", role: l("Temazcal y herbolaria", "Temazcal and herbal medicine"), tags: [l("Temazcal", "Temazcal"), l("Cultural", "Cultural")], photo: null, tone: "#9C4A2F", visible: true, sortOrder: 2 },
    { id: "p3", name: "Rodrigo", role: l("Cuevas y bici de montaña", "Caves and mountain biking"), tags: [l("Cuevas", "Caves"), l("Ruta bici", "Bike route")], photo: null, tone: "#3F5C5E", visible: true, sortOrder: 3 },
    { id: "p4", name: "Ximena", role: l("Cabalgata y cascadas", "Horseback rides and waterfalls"), tags: [l("Cabalgata", "Horseback Ride"), l("Cascadas", "Waterfalls")], photo: null, tone: "#8F6E42", visible: true, sortOrder: 4 },
  ],
  faqs: [
    { id: "f1", q: l("¿Cómo reservo un tour?", "How do I book a tour?"), a: l("Toca «Reservar» en el tour que te guste: se abrirá WhatsApp con un mensaje listo. Te confirmamos fecha, hora y punto de encuentro en minutos.", "Tap “Book” on the tour you like: WhatsApp will open with a ready-made message. We'll confirm the date, time and meeting point within minutes."), visible: true, sortOrder: 1 },
    { id: "f2", q: l("¿Cómo se paga?", "How do I pay?"), a: l("No cobramos en línea. Al confirmar tu lugar por WhatsApp te explicamos las formas de pago disponibles.", "We don't take online payments. When we confirm your spot on WhatsApp, we'll explain the payment options."), visible: true, sortOrder: 2 },
    { id: "f3", q: l("¿Qué pasa si llueve?", "What if it rains?"), a: l("Si el clima no es seguro, reprogramamos tu tour sin costo o te proponemos otra actividad.", "If the weather isn't safe, we'll reschedule your tour at no cost or suggest another activity."), visible: true, sortOrder: 3 },
    { id: "f4", q: l("¿Pueden ir niñas y niños?", "Can children come?"), a: l("Sí, en los tours de dificultad fácil. Escríbenos y te recomendamos el mejor según la edad.", "Yes, on the easy tours. Message us and we'll recommend the best one for their age."), visible: true, sortOrder: 4 },
    { id: "f5", q: l("¿Dónde es el punto de encuentro?", "Where is the meeting point?"), a: l("La mayoría de los tours salen del centro de Tepoztlán. Te enviamos la ubicación exacta al reservar.", "Most tours leave from downtown Tepoztlán. We'll send you the exact location when you book."), visible: true, sortOrder: 5 },
    { id: "f6", q: l("¿Qué debo llevar?", "What should I bring?"), a: l("Ropa cómoda, calzado para caminar, agua y protector solar. Cada tour tiene su propia lista en «Qué llevar».", "Comfortable clothes, walking shoes, water and sunscreen. Each tour has its own list under “What to bring”."), visible: true, sortOrder: 6 },
  ],
  texts: {},
  publishedAt: null,
};
